#! /bin/sh

test -d $HOME/lixo || mkdir $HOME/lixo
test 0 -eq "$#" && exit 1;
case $1 in
	-l) ls $home/lixo
	-r) case $# in
		1)  aux=$PWD; cd $HOME/lixo; rm -rf *; cd \$aux;;
		*) echo pro_lixo: Uso incorreto;;
	*) for i in $*
		do
			if test -f $i
				then mv $i $HOME/lixo
				else echo pro_lixo: Arquivo $i nao encontrado
			fi
		done;;
esac
